# Author Guidelines {-}

<span style="color: red;">ALL CONTENT IN THIS REPORT IS PRELIMINARY AND DRAFT. DO NOT REFERENCE FOR ANY PURPOSE.</span>

Level setting at the beginning. This is what the manual does. A reader should take away the following. Chapters need to give this information so the reader is walking away with practitioner guidance. 
This what the manual does not do. 

What do we want of people? Insert content on issues like:  

- ASCE MOP process and style guide.  
- Decision process  
- Style. How consistent is the structure across chapters? Probably variable content. Consistent level of detail in terms of length. Provide general word count and number of figures/tables; these are order-of-magnitude targets. Max of one graphic device per 500 words.  
- Content. How much lit review and case study? What is the tone? Directing the authors to representative resources (e.g., AASHTO green book). Manual will have an instructional tone. Providing example paragraphs with contrasting tone. Case study examples are helpful, but need to be limited to clearly demonstrative issues (perhaps one call-out box per chapter?).
- Formatting. Color schemes, page orientation, etc.   
- Figures and tables. Graphics and visuals? Limitations or differences for print layout?  
- Document download and editing. Workflow for collaboration on drafts and upload to ebook. Author teams develop drafts and periodically send to editorial team for archival on ASCE server. 
