---
title: "Using R for ecological modeling in USACE"
author: "Ed Stowe"
site: bookdown::bookdown_site
\documentclass: book
output:
  #bookdown::gitbook: default
  bookdown::bs4_book: default
github-repo: USACE-WRISES/USACE.EcoMod.Training
---

# Using R for ecological modeling in USACE restoration planning {-}

## Motivation {-}
Ecological models are an important tool for ecosystem restoration planning within the U.S. Army Corps of Engineers. Models are used to estimate the ecosystem benefits of different restoration alternatives or projects. Ecosystem benefits are coupled with cost data to identify cost effective plans at different price levels, and to ultimately select restoration plans to undertake. So, the outputs of ecological models are very important in determining what projects are built! However, ecological modeling within USACE is primarily a spreadsheet-based activity featuring deterministic habitat models. The ecological modeling capacity of USACE biologists can be greatly improved by incorporating modern data science practices, especially the uptake of R, a programming language that is used in the majority of ecological research being conducted today. R promotes research that is well-documented, reproducible, interdisciplinary, and extensible. R also works on all kinds of data, produces high-quality graphics, has a broad supportive network of users, and is easier to learn than ever before. This training series will focus on teaching USACE biologists and other practitioners how to use R for ecological modeling. Doing so can yield numerous benefits for restoration planning, from improved communication to more accurate model estimates and increased insight into uncertainty.

## Intended audience {-}
* Modeling experience: Those considering themselves “modelers” on projects, with some familiarity with ecological modeling, or wanting to expand their modeling toolbox. Those open to learning how to use code.
* Career trajectory: USACE planners, biologists, and geospatial analysts; this course may also benefit ecological/environmental engineers who want to work with data, produce data-driven reports, or generate compelling graphs.
* Institutional context: USACE team members; partners working closely with USACE.
* Pre-requisites: None! Some familiarity with ecological models and how they are used in USACE may be useful, but some of this understanding can be derived from the material. Similarly, experience with numerical modeling, coding, and data analysis may also help but is not required.

## Learning objectives {-}
* Become familiar with R coding basics, the RStudio environment, and the benefits of using R for conducting analyses.
* Learn some important building blocks of data “wrangling” and visualization in R.
* Learn key methods for seeking help with R coding problems.
* Increase familiarity with existing habitat modeling tools.
* Develop ability to conduct some non-habitat ecological modeling and compare with traditional habitat models.
* Learn how to use R for other data science tasks, such as accessing public data online and conducting reproducible research.

## Module format {-}
Asynchronous, self-directed modules accompanied by R code to carry out analyses. This format was selected because it is:

* Durable (i.e., tutorials persist online)  
* Flexible for learners  
* Has potential impact beyond USACE  

## Module structure {-}
Module structure varies but many modules have the following content:
* Background for context (5-15 minutes)
* Coding mechanics (10-20 minutes)
* Application of the code to a case study (10-30 minutes)

## Additional resources to be provided by instructors {-}
* Potential zoom “office hours” to assist trainees with coding and data troubleshooting. To inquire about this, contact the tutorial organizer listed below.
* Links to vetted resources for working with R, RStudio, and ecological models

## Course subject matter {-}

The training course will include modules that introduce users to coding in R, followed by modules that focus on different ecological modeling topics. Users who are already proficient with R and RStudio but wish to learn more about ecological modeling may skip directly to specific modules relevant to their goals.

Modules on the basics of using R and RStudio (modules 1 through 4) are adapted from an open-source course entitled [Data Analysis and Visualization in R for Ecologists](https://datacarpentry.github.io/R-ecology-lesson/introduction-r-rstudio.html)^[Sections using this source are licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) by the authors which enables its adaptation. This material is Copyright (c) Data Carpentry] created by [The Carpentries](https://carpentries.org/), a community of instructors and trainers who teach foundational data science skills to other researchers. This course is designed for a ~6 hour workshop, but has also been adapted into multiple standalone videos (e.g., [here](https://www.youtube.com/watch?v=AJKd8Av6uoQ&list=PLwFqvDRX_4sJ0HnNGXlWjd8A7vFi2k0wp&index=8)); we divide these workshop materials into four modules.

## Contact us! {-}

The current editor and organizer of this material is Ed Stowe, an ecologist and ORISE Postdoctoral Fellow at USACE ERDC Environmental Lab. For inquiries about the material or requests to help, feel free to contact him at: edward.s.stowe AT erdc.dren.mil
